### ISSUE TITLE
vuejs 报 maxHeight 错误

### ISSUE THREAD

**Issue by roy-lau** [doterlin/vue-wxChat#6]
![image](https://user-images.githubusercontent.com/22829291/86993353-603d1780-c1d6-11ea-9339-570250c0479e.png)

https://github.com/doterlin/vue-wxChat/blob/8901cee030452761d5f4a4db780e2e815486d938/src/components/wxChat.vue#L299

**Comment by roy-lau** [comment]
![image](https://user-images.githubusercontent.com/22829291/86994393-d8a4d800-c1d8-11ea-87b1-ec62e0656478.png)
直接 clone 这个仓库运行后也会报这样的错误

**Comment by doterlin** [comment]
是否影响功能，如是你可以按照这条warn里面的指示去改下代码。
再或者是vue版本的问题，你可以指定早期一些的版本（按照package.js）安装vue版本

**Comment by roy-lau** [comment]
不影响功能，只是 vuejs 会有 warn

https://cn.vuejs.org/v2/guide/components-props.html#%E5%8D%95%E5%90%91%E6%95%B0%E6%8D%AE%E6%B5%81

![image](https://user-images.githubusercontent.com/22829291/86998904-f1ff5180-c1e3-11ea-9507-141162839bbd.png)
`vue` 不允许在一个子组件内部改变 `prop`

**Comment by roy-lau** [comment]
我自己解决了
closed。。。
